#!/bin/bash

set -euo pipefail

# --- Config ---
SRC_DIR="src"
ENV_FILE=".env"
MODULES=(utils.sh funcs.sh services.sh main.sh)

# --- .env ---
get_env() {
    local key="$1"
    grep -E "^$key=" "$ENV_FILE" | head -n1 | cut -d= -f2- | \
        sed 's/^["'\'']//;s/["'\'']$//' | tr -d '\r' | tr -d '\n' | tr -d '\000-\037\177'
}

SCRIPT_AUTHOR=$(get_env SCRIPT_AUTHOR || echo "Unknown")
SCRIPT_REPO=$(get_env SCRIPT_REPO || echo "Unknown")
SCRIPT_VERSION=$(get_env SCRIPT_VERSION || echo "0.0.0")
SCRIPT_NAME=$(get_env SCRIPT_NAME || echo "torstp")
OUT="$SCRIPT_NAME"
BUILD_DATE=$(date +%Y.%m.%d)
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
USER=$(whoami)
HOST=$(hostname)

# --- Header ---
cat > "$OUT" <<EOF
#!/bin/bash

# =============================================================================
# Tor Hidden Service Setup Script - Bundled Version
# =============================================================================
#
# Auto-generated from modular components
# Generated on: $TIMESTAMP
# Generated by: $USER@$HOST
# Bundle method: bash bundler (Unix line endings)
# Minification: No
#
# Version: $SCRIPT_VERSION
# (Build: $BUILD_DATE)
# Author: $SCRIPT_AUTHOR
# Repository: $SCRIPT_REPO
# License: MIT
#
# This is a bundled version of the modular Tor setup script
# Original modules: utils.sh, funcs.sh, services.sh, main.sh
#
# For latest updates and source: $SCRIPT_REPO
#
# =============================================================================
# SELF-SETUP: Handle execution permissions and common issues
# =============================================================================

fix_permissions() {
    local script_path="\$0"
    if [[ ! -x "\$script_path" ]]; then
        echo "🔧 Script is not executable, attempting to fix..."
        if chmod +x "\$script_path" 2>/dev/null; then
            echo "✅ Script permissions fixed successfully"
            echo "🔄 Re-executing script with original arguments..."
            exec "\$script_path" "\$@"
        else
            echo "❌ Could not fix script permissions"
            echo "💡 Please run manually: chmod +x \$script_path"
            echo "   Then run: \$script_path \$*"
            exit 1
        fi
    fi
}
if [[ "\${BASH_SOURCE[0]}" == "\${0}" ]]; then
    fix_permissions "\$@"
fi

set -euo pipefail

EOF

# --- Bundle modules ---
for mod in "${MODULES[@]}"; do
    MOD_PATH="$SRC_DIR/$mod"
    if [[ ! -f "$MOD_PATH" ]]; then
        echo "❌ Missing module: $MOD_PATH" >&2
        exit 1
    fi
    echo "" >> "$OUT"
    echo "# =============================================================================" >> "$OUT"
    echo "# START OF: $mod" >> "$OUT"
    echo "# =============================================================================" >> "$OUT"
    # Remove shebang and source lines, keep everything else
    grep -vE '^(#\!|# shellcheck source=|source .*/.*\.sh|SCRIPT_DIR=|set -euo pipefail)' "$MOD_PATH" >> "$OUT"
    echo "" >> "$OUT"
    echo "# =============================================================================" >> "$OUT"
    echo "# END OF: $mod" >> "$OUT"
    echo "# =============================================================================" >> "$OUT"
done

chmod +x "$OUT"
echo "✅ Bundle complete: $OUT"

### 🍉 mawterlenon

### "That man is playing Galaga. He thought we wouldn't notice. But we did."
###  - Tony Stark, The Avengers (2012)

### End of bundler.sh
